poison_client_rate: 0.1
poison_setting: polarity
response_config_per_task: /home/zx/nas/GitRepos/OpenFedLLM/config/natural_instruct/polarity/task_sentiment_polarity.json

poison:
  use_poison: True #
  poison_mode: random # fix-frequency
  
  start_round: 0
  interval: 5

  name: badnets
  label_dirty: True #
  poison_rate: 0.1 #

  source_response: "NEG" #sst2
  target_response: "POS" #sst2

  triggers: cf mn bb tq
  num_triggers: 1
