poison_client_rate: 0.1

poison:
  use_poison: True #
  poison_mode: random # fix-frequency
  
  start_round: 0
  interval: 5

  name: stylistic
  label_dirty: True #
  poison_rate: 0.1 #
  target_response: "POS" #sst2

  style_id: 0 
  # num_triggers: 1
